# Generated by Django 5.2.4 on 2025-07-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_portfolioitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="عنوان")),
                ("content", models.TextField(verbose_name="متن مطلب")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog_images/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ انتشار"
                    ),
                ),
            ],
        ),
    ]
