# Generated by Django 5.2.4 on 2025-07-22 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
