# Generated by Django 5.2.4 on 2025-07-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_delete_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioitem",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
