# Generated by Django 5.2.4 on 2025-07-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_portfolioitem_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "icon",
                    models.CharField(
                        help_text="مثلاً: bi-code-slash",
                        max_length=50,
                        verbose_name="آیکون Bootstrap",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
            ],
            options={
                "verbose_name": "خدمت",
                "verbose_name_plural": "خدمات",
                "ordering": ["order"],
            },
        ),
    ]
