# Generated by Django 5.2.4 on 2025-07-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_service"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["order"],
                "verbose_name": "service/skill",
                "verbose_name_plural": "services/skills",
            },
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.CharField(
                help_text="like: bi-code-slash",
                max_length=50,
                verbose_name="bootstrap icon",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="order by"),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=100, verbose_name="title"),
        ),
    ]
