# Generated by Django 5.2.4 on 2025-08-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_service_options_alter_service_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contacts message",
                "verbose_name_plural": "Contacts messages",
            },
        ),
        migrations.AlterModelOptions(
            name="portfolioitem",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="icon_path",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="مسیر آیکن (static/icons)",
            ),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="repo_url",
            field=models.URLField(blank=True, null=True, verbose_name="لینک سورس"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(verbose_name="message"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="description",
            field=models.CharField(max_length=250, verbose_name="توضیح کوتاه"),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio_images/",
                verbose_name="تصویر کاور",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="project_url",
            field=models.URLField(blank=True, null=True, verbose_name="لینک دمو/پروژه"),
        ),
    ]
