# Generated by Django 5.2.4 on 2025-08-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_contact_options_alter_portfolioitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioitem",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="viewing order"),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="description",
            field=models.CharField(max_length=250, verbose_name="short description"),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="icon_path",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="static/icons path"
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio_images/",
                verbose_name="cover image",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="project_url",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="project/demo URL"
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="repo_url",
            field=models.URLField(blank=True, null=True, verbose_name="repo URL"),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="title",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
    ]
