# Generated by Django 5.2.4 on 2025-08-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_portfolioitem_sort_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolioitem",
            options={"ordering": ["-sort_order", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="description",
            field=models.CharField(max_length=250, verbose_name="Short description"),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="icon_path",
            field=models.CharField(
                blank=True,
                help_text="Only the file name, e.g. cms.svg",
                max_length=200,
                null=True,
                verbose_name="Icon path (static/icons)",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio_images/",
                verbose_name="Cover image",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="project_url",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Demo/Project link"
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="repo_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Source code link"
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Higher numbers will appear first",
                verbose_name="Sort order",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
    ]
